[sources.sql_database.credentials]

#credentials="mssql://sqldwhprod:sql1234*@bodsql\bi01:1433/nmbsta?driver=ODBC+Driver+18+for+SQL+Server&Encrypt=yes&encrypt=true&TrustServerCertificate=yes"
driver = "{ODBC Driver 18 for SQL Server}" #"mssql+pyodbc" # fill this in!
database = "" # fill this in!
pwd = "" # fill this in!
uid = "" # fill this in!
server = "" # fill this in!
port = 1433 # fill this in!


##"credentials = (
##    "mssql+pyodbc:///?"
##    "odbc_connect="
##    "DRIVER={ODBC Driver 18 for SQL Server};"
##    "SERVER=bodsql\\bi01;"
##    "DATABASE=nmbsta;"
##    "UID=sqldwhprod;"
##    "PWD=sql1234*;"
##    "Encrypt=yes;"
##    "TrustServerCertificate=yes;"
##)
#
[destination.snowflake.credentials]
database = "raw" # fill this in!
password = "Jesus&Marie@137" # fill this in!
username = "jsgane" # fill this in!
host = "HLMXIPC-CGB22633" # fill this in!
warehouse = "compute_wh" # fill this in!
role = "sysadmin" # fill this in!
